apiVersion: v1
kind: PersistentVolume
metadata:
  name: clairviewcrm-docker-data-pv
spec:
  storageClassName: default
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
