apiVersion: v1
kind: PersistentVolume
metadata:
  name: clairviewcrm-server-pv
  namespace: clairviewcrm
spec:
  storageClassName: default
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
