apiVersion: v1
kind: Service
metadata:
  name: clairviewcrm-redis
  namespace: clairviewcrm
spec:
  internalTrafficPolicy: Cluster
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: clairviewcrm-redis
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP
