#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Welcome to the Clairview DigitalOcean 1-Click Droplet.
To keep this Droplet secure, the UFW firewall is enabled.
All ports are BLOCKED except 22 (SSH), 80 (HTTP), 443 (HTTPS), and 10000 

* Clairview website: http://clairview.com

For help and more information, visit https://docs.clairview.com/docs/digitalocean

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
