apiVersion: v2
name: clairview
description: >-
  Clairview is an open source low-code platform, helping thousands of teams build
  apps for their workplace in minutes.
keywords:
  - low-code
  - database
  - cluster
sources:
  - https://github.com/clairview/clairview
  - https://clairview.com
type: application
# populates on packaging
version: 0.0.0
# populates on packaging
appVersion: 0.0.0
dependencies:
  - name: couchdb
    version: 4.5.6
    repository: https://apache.github.io/couchdb-helm
    condition: services.couchdb.enabled
