{{- if .Values.extraSecretEnvs }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clairview.fullname" . }}
  labels:
    {{- include "clairview.labels" . | nindent 4 }}
data:
  NC_DB: {{ include "databaseUri" . | b64enc}}
{{- range $key, $value := .Values.extraSecretEnvs }}
  {{ $key }}: '{{ $value | b64enc }}'
{{- end }}
{{- end }}
