export enum Header {
  API_KEY = "x-clairview-api-key",
  LICENSE_KEY = "x-clairview-license-key",
  API_VER = "x-clairview-api-version",
  APP_ID = "x-clairview-app-id",
  SESSION_ID = "x-clairview-session-id",
  TYPE = "x-clairview-type",
  PREVIEW_ROLE = "x-clairview-role",
  TENANT_ID = "x-clairview-tenant-id",
  VERIFICATION_CODE = "x-clairview-verification-code",
  RETURN_VERIFICATION_CODE = "x-clairview-return-verification-code",
  RESET_PASSWORD_CODE = "x-clairview-reset-password-code",
  RETURN_RESET_PASSWORD_CODE = "x-clairview-return-reset-password-code",
  TOKEN = "x-clairview-token",
  CSRF_TOKEN = "x-csrf-token",
  CORRELATION_ID = "x-clairview-correlation-id",
  AUTHORIZATION = "authorization",
  MIGRATING_APP = "x-clairview-migrating-app",
  COOKIE = "cookie",
}
